# Docker Compose file to setup the ChagasDB Web Server
# Don't forget to point the volume on your folder with the sqlite file

web:
  build: .
  command: >
      sh -c "export DB_FILE=/data/db.sqlite3 &&
             export CHAGAS_VERSION=v.0.0.1 &&
             export ALLOWED_HOSTS=chagasdb.tagc.univ-amu.fr &&
             python manage.py runserver 0.0.0.0:8000"
  volumes:
    - ../chagasDB_data:/data
  ports:
    - "80:8000"
