# Generated by Django 4.0.7 on 2022-11-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_chagas_object_doi_alter_chagas_object_paper_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chagas_object',
            name='fold_change',
        ),
        migrations.AddField(
            model_name='chagas_object',
            name='feature_variation',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
